# Generated by Django 3.2.9 on 2021-11-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondYld',
            fields=[
                ('date', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('bond_type', models.CharField(max_length=4)),
                ('three_month', models.CharField(max_length=4)),
                ('six_month', models.CharField(max_length=4)),
                ('nine_month', models.CharField(max_length=4)),
                ('one_year', models.CharField(max_length=4)),
                ('one_year_half', models.CharField(max_length=4)),
                ('two_year', models.CharField(max_length=4)),
                ('three_year', models.CharField(max_length=4)),
                ('five_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='YldDeviation',
            fields=[
                ('dv_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dv_value', models.CharField(max_length=25)),
                ('fk_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bondapp.bondyld')),
            ],
        ),
    ]
