# Generated by Django 3.2.9 on 2021-11-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondYld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('bond_type', models.CharField(max_length=4)),
                ('three_month', models.CharField(max_length=4)),
                ('six_month', models.CharField(max_length=4)),
                ('nine_month', models.CharField(max_length=4)),
                ('one_year', models.CharField(max_length=4)),
                ('one_year_half', models.CharField(max_length=4)),
                ('two_year', models.CharField(max_length=4)),
                ('three_year', models.CharField(max_length=4)),
                ('five_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'bond_yld',
            },
        ),
        migrations.CreateModel(
            name='YldDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_value', models.CharField(max_length=25)),
                ('int_cycle', models.CharField(max_length=10)),
                ('bond_yld_id', models.ForeignKey(db_column='bond_yld_id', on_delete=django.db.models.deletion.CASCADE, to='bondapp.bondyld')),
            ],
            options={
                'db_table': 'yld_deviation',
            },
        ),
    ]
