# Generated by Django 3.2.9 on 2021-11-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bondyld',
            table='bond_yld',
        ),
        migrations.AlterModelTable(
            name='ylddeviation',
            table='yld_deviation',
        ),
    ]
